# Generated by Django 2.2.4 on 2019-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='tests.TestQuestion'),
        ),
        migrations.AlterField(
            model_name='testquestion',
            name='answer',
            field=models.ManyToManyField(blank=True, null=True, to='tests.PossibleAnswer'),
        ),
    ]
